### ISSUE TITLE
This EFI can be update big sur? 

### ISSUE THREAD

**Issue by lhc87227** [tomtcy1989/Hackintosh-Asus-P8Z77-V-LX-OpenCore#1]
This u, i have p8z77, but can't close cfg lock, its don't work for big sur

**Comment by lhc87227** [comment]
> Thinks u, i have p8z77, but can't close cfg lock, its don't work for big sur

Do you know what to do?

**Comment by tomtcy1989** [comment]
Hi there, I don't think there's CFG lock option in our boards' BIOS settings. So based on Dortania guide, you can enable the below options in config.plist Kernel - Quirks 

AppleCpuPmCfgLock AppleXcpmCfgLock

https://dortania.github.io/OpenCore-Install-Guide/config.plist/ivy-bridge.html#kernel

I updated Big Sur with no issues.

**Comment by tomtcy1989** [comment]
> > Thinks u, i have p8z77, but can't close cfg lock, its don't work for big sur
> 
> Do you know what to do?

Hi there, I don't think there's CFG lock option in our boards' BIOS settings. So based on Dortania guide, you can enable the below options in config.plist Kernel - Quirks

AppleCpuPmCfgLock AppleXcpmCfgLock

https://dortania.github.io/OpenCore-Install-Guide/config.plist/ivy-bridge.html#kernel

I updated Big Sur with no issues.

**Comment by lhc87227** [comment]
Yep,i use u EFI updated Big Sur! Perfect!
Super thanks！Hope u can keep updating~

**Comment by tomtcy1989** [comment]
> Yep,i use u EFI updated Big Sur! Perfect!
> Super thanks！Hope u can keep updating~

Glad that I could help. Happy Hackintoshing.

**Comment by peppefender** [comment]
Hi! Thanks for your files!

I have the same board as yours, but i5 2400 as cpu. Using your files, it gaves me black screen and no OpenCore IU shows at all.

Have you ever get this issue?

**Comment by tomtcy1989** [comment]
> Hi! Thanks for your files!
> 
> I have the same board as yours, but i5 2400 as cpu. Using your files, it gaves me black screen and no OpenCore IU shows at all.
> 
> Have you ever get this issue?

No I didn't experience this. The main issue here I assume would be your unsupported iGPU. Try getting a supported dGPU would resolve the issue potentially. Also I think your CPU is also a generation older than mine. Following Dortania guide according to your CPU would be my best bet.

**Comment by peppefender** [comment]
Thanks for the reply!

I've disabled the iGPU and I'm using a AMD r7 260x.

I've followed the Dortania guide, but unfortunately I'm always stucked on black screen.

**Comment by tomtcy1989** [comment]
> Thanks for the reply!
> 
> I've disabled the iGPU and I'm using a AMD r7 260x.
> 
> I've followed the Dortania guide, but unfortunately I'm always stucked on black screen.

https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#r7-r9
Have a look at this section of the guide and try different ports e.g. from HDMI to DP/DVI. I cannot help you much from here as I don't have this card to test. You might need to start researching on 260x Opencore blackscreen

**Comment by peppefender** [comment]
Thanks!

I'll check for it!
